[project]
name = "gradio-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.32.0",
    "joblib>=1.5.1",
    "matplotlib>=3.10.3",
    "natasha>=1.6.0",
    "scikit-learn>=1.6.1",
]
